import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Template: NextPage = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{children}</main>
    </div>
  );
};

export default Template;
