import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Template: NextPage = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav>
          <ul>
            <li>
              <Link href="/">
                <a>Olá</a>
              </Link>
            </li>
            <li>
              <Link href="/blog">
                <a>Blog</a>
              </Link>
            </li>
            <li>
              <Link href="/contact">
                <a>Contact</a>
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </main>
    </div>
  );
};

export default Template;
